import {StyleSheet} from 'react-native';
import { width,height } from '../strings';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor:white ,
  },
  scrollViewContainer: {
    width: width - 40,
    height: height,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dividerLiner: {
    borderBottomWidth: 1,
    marginBottom: 20,
    borderBottomColor: '#D4D4D4',
  },
  imageUploadContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    marginLeft: 10,
  },
  imageUploadIconContainer: {
    position: 'relative',
    borderRadius: 20,
    height: 40,
    width: 40,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#fff',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  cameraText: {
    color: '#000',
    fontSize: 16,
    padding: 12,
  },
  row: {
    flexDirection: 'row',
  },
  navbtn: {
    marginTop: 15,
  },
  forgotbtn: {
    marginVertical: 35,
  },
  navbtntext: {
    fontSize: 15,
    fontWeight: '500',
    color: '#949fa7',
  },
  actioncontainer: {
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: '#2e64e5',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  addIconConatiner: {
    bottom: '25%',
    left: '75%',
    backgroundColor: '#fff',
    width: 26,
    height: 26,
    borderRadius: 26 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {paddingLeft: 8, backgroundColor: '#fff'},
  textInput: {
    flex: 1,
    padding: 10,
    color: '#333333',
    width: '100%',
    height: 30,
    backgroundColor: '#fff',
  },
  profileImageConatiner: {
    height: 100,
    width: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dividerConatiner: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dividerLine: {
    flexDirection: 'row',
    borderWidth: 0.2,
    borderColor: '#9b9b9b',
    width: '42%',
    height: 0,
  },
  dividerText: {
    color: '#9b9b9b',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 12,
    marginRight: 12,
  },
  imgbg: {
    height: 100,
    width: 100,
    borderRadius: 50,
  },
  chooseimg: {
    textAlign: 'center',
    padding: 6,
    fontSize: 18,
    color: '#000',
  },
});
